services:
  - type: web
    name: referrer-tracker
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /landing

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://referrer-tracker.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      # <- cheia magică: URL complet cu SSL din baza Render
      - key: DATABASE_URL
        fromDatabase:
          name: referrer-db
          property: connectionStringStandardSsl
      # APP_KEY îl setezi din Dashboard (nu în yaml)

databases:
  - name: referrer-db
    plan: free
