services:
  - type: web
    name: referrer-tracker
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /landing
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://referrer-tracker.onrender.com   # actualizează după primul deploy cu URL-ul real
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      # APP_KEY se setează din Dashboard (NU în repo)

databases:
  - name: referrer-db
    plan: free
